Issue
  { issueClosedAt = Just 2016 (-07) (-20) 23 : 10 : 30 UTC
  , issueUpdatedAt = 2016 (-07) (-20) 23 : 10 : 30 UTC
  , issueEventsUrl =
      "https://api.github.com/repos/rethinkdb/docs/issues/1153/events"
  , issueHtmlUrl =
      Just "https://github.com/rethinkdb/docs/issues/1153"
  , issueClosedBy = Nothing
  , issueLabels = []
  , issueNumber = 1153
  , issueAssignee =
      Just
        SimpleUser
          { simpleUserId = Id 467928
          , simpleUserLogin = N "chipotle"
          , simpleUserAvatarUrl =
              "https://avatars.githubusercontent.com/u/467928?v=3"
          , simpleUserUrl = "https://api.github.com/users/chipotle"
          , simpleUserType = OwnerUser
          }
  , issueUser =
      SimpleUser
        { simpleUserId = Id 1777134
        , simpleUserLogin = N "mlucy"
        , simpleUserAvatarUrl =
            "https://avatars.githubusercontent.com/u/1777134?v=3"
        , simpleUserUrl = "https://api.github.com/users/mlucy"
        , simpleUserType = OwnerUser
        }
  , issueTitle =
      "https://www.rethinkdb.com/api/javascript/run/ has an incorrect example"
  , issuePullRequest = Nothing
  , issueUrl =
      "https://api.github.com/repos/rethinkdb/docs/issues/1153"
  , issueCreatedAt = 2016 (-07) (-10) 02 : 16 : 51 UTC
  , issueBody =
      Just
        "In the both of the promises examples, we write `.error` instead of `.catch`."
  , issueState = "closed"
  , issueId = Id 164695401
  , issueComments = 0
  , issueMilestone = Nothing
  }