Issue
  { issueClosedAt = Just 2013 (-10) (-28) 17 : 34 : 09 UTC
  , issueUpdatedAt = 2013 (-10) (-28) 17 : 34 : 09 UTC
  , issueEventsUrl =
      "https://api.github.com/repos/rethinkdb/docs/issues/37/events"
  , issueHtmlUrl = Just "https://github.com/rethinkdb/docs/issues/37"
  , issueClosedBy = Nothing
  , issueLabels = []
  , issueNumber = 37
  , issueAssignee = Nothing
  , issueUser =
      SimpleUser
        { simpleUserId = Id 91193
        , simpleUserLogin = N "mglukhovsky"
        , simpleUserAvatarUrl =
            "https://avatars.githubusercontent.com/u/91193?v=3"
        , simpleUserUrl = "https://api.github.com/users/mglukhovsky"
        , simpleUserType = OwnerUser
        }
  , issueTitle = "API: `next` 404s for Python and Ruby"
  , issuePullRequest = Nothing
  , issueUrl =
      "https://api.github.com/repos/rethinkdb/docs/issues/37"
  , issueCreatedAt = 2013 (-10) (-26) 00 : 07 : 02 UTC
  , issueBody =
      Just
        "`next` and other commands need to have YAML flags to indicate they don't exist in other languages. They currently 404 because links in the language switcher are active."
  , issueState = "closed"
  , issueId = Id 21623455
  , issueComments = 1
  , issueMilestone = Nothing
  }