Issue
  { issueClosedAt = Just 2015 (-04) (-30) 22 : 59 : 52 UTC
  , issueUpdatedAt = 2015 (-04) (-30) 22 : 59 : 52 UTC
  , issueEventsUrl =
      "https://api.github.com/repos/rethinkdb/docs/issues/729/events"
  , issueHtmlUrl =
      Just "https://github.com/rethinkdb/docs/issues/729"
  , issueClosedBy = Nothing
  , issueLabels = []
  , issueNumber = 729
  , issueAssignee =
      Just
        SimpleUser
          { simpleUserId = Id 467928
          , simpleUserLogin = N "chipotle"
          , simpleUserAvatarUrl =
              "https://avatars.githubusercontent.com/u/467928?v=3"
          , simpleUserUrl = "https://api.github.com/users/chipotle"
          , simpleUserType = OwnerUser
          }
  , issueUser =
      SimpleUser
        { simpleUserId = Id 505365
        , simpleUserLogin = N "danielmewes"
        , simpleUserAvatarUrl =
            "https://avatars.githubusercontent.com/u/505365?v=3"
        , simpleUserUrl = "https://api.github.com/users/danielmewes"
        , simpleUserType = OwnerUser
        }
  , issueTitle =
      "Update documentation for writing drivers to include ResponseNotes"
  , issuePullRequest = Nothing
  , issueUrl =
      "https://api.github.com/repos/rethinkdb/docs/issues/729"
  , issueCreatedAt = 2015 (-04) (-23) 19 : 06 : 02 UTC
  , issueBody =
      Just
        "Moved from https://github.com/rethinkdb/rethinkdb/issues/4093.\r\n\r\n@hamiltop wrote:\r\n> See 62bbf33bed1950103df43ed272458f93f60b7221 \r\n> \r\n> The documentation on writing drivers still has `SUCCESS_FEED` which no longer exists in master. Ran me around in circles trying to figure out what why `changes()` wasn't returning a `SUCCESS_FEED`."
  , issueState = "closed"
  , issueId = Id 70487732
  , issueComments = 2
  , issueMilestone = Nothing
  }