Issue
  { issueClosedAt = Just 2015 (-06) (-04) 22 : 15 : 09 UTC
  , issueUpdatedAt = 2015 (-06) (-04) 22 : 15 : 09 UTC
  , issueEventsUrl =
      "https://api.github.com/repos/rethinkdb/docs/issues/784/events"
  , issueHtmlUrl =
      Just "https://github.com/rethinkdb/docs/issues/784"
  , issueClosedBy = Nothing
  , issueLabels =
      [ IssueLabel
          { labelColor = "f7c6c7"
          , labelUrl =
              "https://api.github.com/repos/rethinkdb/docs/labels/api"
          , labelName = "api"
          }
      ]
  , issueNumber = 784
  , issueAssignee =
      Just
        SimpleUser
          { simpleUserId = Id 467928
          , simpleUserLogin = N "chipotle"
          , simpleUserAvatarUrl =
              "https://avatars.githubusercontent.com/u/467928?v=3"
          , simpleUserUrl = "https://api.github.com/users/chipotle"
          , simpleUserType = OwnerUser
          }
  , issueUser =
      SimpleUser
        { simpleUserId = Id 7431361
        , simpleUserLogin = N "larkost"
        , simpleUserAvatarUrl =
            "https://avatars.githubusercontent.com/u/7431361?v=3"
        , simpleUserUrl = "https://api.github.com/users/larkost"
        , simpleUserType = OwnerUser
        }
  , issueTitle =
      "wait documentation should mention the error thrown on timeout"
  , issuePullRequest = Nothing
  , issueUrl =
      "https://api.github.com/repos/rethinkdb/docs/issues/784"
  , issueCreatedAt = 2015 (-06) (-04) 05 : 26 : 26 UTC
  , issueBody =
      Just
        "Our current documentation on the `wait` command does not mention what happens when a `timeout` value is exceeded (we throw a `RqlRuntimeError` error). We should also mention that giving `0` is a way of getting the default (no timeout) behavior."
  , issueState = "closed"
  , issueId = Id 84922082
  , issueComments = 0
  , issueMilestone = Nothing
  }